### PR TITLE
Prevent flashing terminal windows on Windows

### LINKED ISSUE #42: cmd popup on Sublime Text WIndows 10 + WSL
ezgif-1-e9165bf71d

This issue was discovered by @girng

Solution proposed by @oprypin :

1. We should replace this line:

https://github.com/crystal-lang-tools/sublime-crystal/blob/d4abc5ab4306ad13a7da2ec974ff927a2ff66bc2/crystal_format.py#L30

2. by something like this:

```python
            if operating_system == 'win':
                # Prevent flashing windows if used from a GUI application
                startupinfo = subprocess.STARTUPINFO()
                startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
                rc = subprocess.call(proc, stdout = pipe, stderr = pipe,
                                     startupinfo = startupinfo)
```

https://github.com/coin-or/pulp/blob/bac6d9d2214ba773d638d2de5149940cfd711359/src/pulp/solvers.py#L378-L382

### PR DESCRIPTION
**Pull request by oprypin**
Fixes #42

### CODE REVIEW

**Comment by oprypin** [comment]
This code is untested. Please try it on some OS, and if it works, I'm quite sure it will work on Windows.

**Comment by faustinoaq** [comment]
@girng Does this fix work for you? Can you review this? :sweat_smile:

**Comment by girng** [comment]
Okay, just tested this on W10, 64-bit.

It works! If I run into any issues I'll make a bug report, thanks @oprypin

**Comment by faustinoaq** [comment]
@girng Ok, Thank you for testing it! :100:  I gonna merge it and do a new release :+1:

**Comment by faustinoaq** [comment]
@fgimian @faultyserver @vladfaust should I merge #45 and #30 before a new release?

**Comment by vladfaust** [comment]
@faustinoaq I'd very like #32 to be fixed first. It's just wrapping exception in Python which I'm not in at all. Please 👏

**Comment by fgimian** [comment]
@faustinoaq I won't lie, I'm not 100% sure how/why my merge request works the way it does but I'm certain that the current behaviour causes errors in the console which are ugly.  My PR really aligns your language definition with the Ruby one, but I don't even know why js is in there 😆 

@vladfaust The exception handling for #32 should be relatively easy to fix, let me see if I can help on that.

**Comment by faustinoaq** [comment]
@fgimian I guess Ruby/Crystal syntax include other syntaxes because heredoc highlighting:

```cr
# crystal with embedded JS
 
my_js_code = <<-JS
function sum(a, b) {
  return a + b
}
JS
``` 

Not only JS highlighting but also `<<-SQL`, `<<-HTML`, `<<-RUBY`, etc, etc :sweat_smile:

**Comment by fgimian** [comment]
Ooooh gotcha 😄 Good point @faustinoaq

**Comment by faustinoaq** [comment]
> I'd very like #32 to be fixed first. It's just wrapping exception in Python which I'm not in at all. 

@vladfaust Yeah no problem. I'll wait, just please be aware I'm not a ST dev. I'm using ST trial version with the sublime-crystal plugin, although I don't have idea about ST plugin development :sweat_smile:

**Comment by fgimian** [comment]
@faustinoaq See my pull request mate, it fixes #32 😄

**Comment by faultyserver** [comment]
@faustinoaq I'd like to see #37, #38, and #40 fixed before a new version is released as well. I think I can get them done pretty quickly today.

**Pull request merged**
