### PR TITLE
Temporary replacement for removed `crystal tool format --format json`

### LINKED ISSUE #63: Crystal 0.27.1 does not work
## Description
This problem causes all features of the plugin to be unavailable.
This problem occurs in 0.27.1 version and higher.

## Version Info
```text
Sublime:
  Version 3.1.1, Build 3176
---
Crystal:
  Crystal 0.27.1 (2019-02-01)
  LLVM: 6.0.1
  Default target: x86_64-apple-macosx
```

## Console Log
```text
Traceback (most recent call last):
  File "./python3.3/json/decoder.py", line 367, in raw_decode
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime.app/Contents/MacOS/sublime_plugin.py", line 1072, in run_
    return self.run(edit)
  File "/Users/User/Library/Application Support/Sublime Text 3/Installed Packages/Crystal.sublime-package/crystal_format.py", line 62, in run
  File "./python3.3/json/__init__.py", line 316, in loads
  File "./python3.3/json/decoder.py", line 351, in decode
  File "./python3.3/json/decoder.py", line 369, in raw_decode
ValueError: No JSON object could be decoded
```

### LINKED ISSUE #64: Change formatter output format from JSON to plain text
`--format` option has been removed in https://github.com/crystal-lang/crystal/pull/7257, and `crystal tool format` is now able to output raw text only. It still can be fetched with Regex. Sadly, but column numbers are gone :cry: 

```sh
Error: Syntax error in ./src/ext/pg/converters/uuid.cr:5: expecting token 'CONST', not 'ds'

      def read(t : ds.class)
```

### PR DESCRIPTION
**Pull request by asterite**
Fixes #63
Fixes #64

The `--format json` was removed (I have no idea why). This is a temporary replacement:
- we obviously don't pass the `--format json` option anymore
- we try to parse the text output to get the line number and error

### CODE REVIEW

**Comment by asterite** [comment]
This is better than #64 because it keeps showing errors when they happen.

**Comment by vladfaust** [comment]
Works for me, thanks, @asterite. As of it's being temporary, should we merge this or even release the new version?

It contains commented code which is ideally should not go into a release version, but we're having a `0.x` version here... :thinking:

**Comment by asterite** [comment]
This should be merged and a new release done. This will always work and it's almost as good as the version that used `--format json`.

**Comment by asterite** [comment]
Thank you Vlad!

**Comment by faustinoaq** [comment]
Tested and working, Thank you @asterite and @vladfaust :+1:

**Pull request merged**
